name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: wasm-pack build --target web --release
      - name: Collect
        run: |
          pwd
          ls
          mkdir ./public
          mv ./pkg ./public/pkg
          mv ./design.html ./public/index.html
          ls
          touch ./public/.git
          ls ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public
