name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: wasm-pack build --target web --release
      - name: Collect
        # Note the `touch public/.something`,
        # this is needed for the actions-gh-pages action to copy the directory
        # for some reason.
        run: |
          mkdir ./public
          mv ./pkg ./public/pkg
          mv ./design.html ./public/index.html
          touch ./public/.nojekyll

      #   - name: Deploy
      #     uses: peaceiris/actions-gh-pages@v3
      #     with:
      #       github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./public"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
